### ISSUE TITLE
sudo

### ISSUE THREAD

**Issue by rmoriz** [higanworks/knife-zero#103]
Hi,

we've the following setup with servers/VM provided by various providers e.g. digitalocean and hetzner:

- new VM/servers are provisioned with a `root` account only 
- `sudo` is not preinstalled (!)

Typically, we bootstrap and converge the nodes which disables root login, so for subsequent converges we want to use `sudo` using freshly created admin-accounts. Therefore we have set `knife[:use_sudo] = true` - but of course this breaks bootstrapping, as `sudo` is not yet installed…

One idea would be to ignore `use_sudo`, when `-x root` is provided or to provide a `--no-sudo` cli option that overwrites the knife.rb setting.

**Comment by sawanoboly** [comment]
I'd like to confirm that my understanding is correct.

1. bootstrap new node with using  `root` without sudo.
2. Bootstrapping installs `sudo` and  creates management user such as `admin`.
3. After bootstrapping, you use `admin` with sudo to converge.

**Comment by sawanoboly** [comment]
`use_sudo` option is provided by chef-core. I'm unwilling to override it.

Could you please consider using user-script to install sudo on boot ?

https://www.digitalocean.com/company/blog/automating-application-deployments-with-user-data/

**Comment by rmoriz** [comment]
In our case it's a dedicated system provider (hetzner.com) which does not provide cloud-init. 

However after reviewing my issue mabye we can just create and use a different `knife.rb` for bootstrapping that does not have `use_sudo` enabled.
