### ISSUE TITLE
knife zero shell

### ISSUE THREAD

**Issue by axos88** [higanworks/knife-zero#104]
Please create a command to get a chef shell on the remote host (or add documentation it it is possible to do).

It would ease debugging cookbooks and inspecting things quite a bit.

**Comment by sawanoboly** [comment]
I think that it is interesting, but in fact it's quite a difficult feature.
I can not take the time for now, so I will look it up even at the end of the year.

**Comment by axos88** [comment]
Can you elaborate why it would be so difficult? It seems like the only thing that would need to be added is to execute chef-shell -z instead of chef-client once connected to the remote machine. Or am I missing something?

**Comment by sawanoboly** [comment]
It is complicated to control the input and output of the terminal used in SSH. If you think it's easy, please make a PullRequest.

**Comment by axos88** [comment]
Ah gotcha. I'll probably play around a bit, when I have some free time. If I make any progress, I'll share.

**Comment by sawanoboly** [comment]
@axos88 

By the way, if you only want to debug a single server, there are the following methods.

First, start chef - zero on the local workstation.

```
$ knife serve
Serving files from:
repository at /Users/sawanoboriyu/develop/src/github.com/higanworks/knife-zero_playglound
  One version per cookbook

>> Starting Chef Zero (v4.6.2)...
>> WEBrick (v1.3.1) on Rack (v1.6.4) is listening at http://localhost:8889
>> Press CTRL+C to stop
```

Next,  open a new terminal. And run chef-shell via SSH with remote forwarding.

`ssh -R 8889:127.0.0.1:8889 ubuntu@remoteserver -i ~/path_to_pem sudo chef-shell -z -S http://127.0.0.1:8889`

or

```
(workstation)$ ssh -R 8889:127.0.0.1:8889 ubuntu@remoteserver -i ~/path_to_pem
(remote_node)$ sudo chef-shell -z -S http://127.0.0.1:8889
```

You can use Chef-Shell with local Chef-Zero connected.


```
Ohai2u ubuntu@sakura-tk01!
chef (12.17.44)> > nodes.all.length
nodes.all.length
 => 8 

chef (12.17.44)> roles.all.length
roles.all.length
 => 6 
```

**Comment by axos88** [comment]
Works, good enough to get the job done.
