### ISSUE TITLE
Questions: attribute usage

### ISSUE THREAD

**Issue by EugenMayer** [higanworks/knife-zero#108]
I have seen in the docs, that there is -j to pass node attributes during converge, but those do not update the local nodes/mynode.json by default, this said, next converge (normal) run those attributes will no longer be present.

How is it designed to use attributes then? How can i apply custom, persistent node-specific attributes? I edited nodes/mynode.json and added normal->attributes->myattribut=foo .. that does not work.

**Comment by sawanoboly** [comment]
>  -j to pass node attributes during converge, but those do not update the local nodes/mynode.json by default

Yes, you're correct about it. These attributes art temporarily used.

And, perhaps it is wrong to edit the contents of the node object. Could you change like below?

```
normal->attributes->myattribut=foo

to

normal->myattribut=foo
```

FYI, the node object bootstrapped is as follows.

```
{
    "name": "test",
    "normal": {
      "knife_zero": {
        "host": "127.0.0.1"
      },   
      "tags": [
  
      ]    
...
```

**Comment by EugenMayer** [comment]
@sawanoboly how would i do this "by design" i mean adding / changing attributes per node is one of the important concepts, right? Or is everything done using wrapper-cookbooks per node?

**Comment by EugenMayer** [comment]
beside that i did https://goo.gl/aBAZ7K and it still does not work, so the attributes are not found. Did i miss something?

**Comment by EugenMayer** [comment]
Interesting, it then works on the second run. Is that a cookbook issue rather then a knife zero issue?

I guess thats all about when those attributes are merged,  right. In the cookbook i use

     node['docker']['registry'].each do |reg_entry|

But those normal attributes are yet not present?

**Comment by EugenMayer** [comment]
Interesting, trying that on a second node, it worked on the first run. I do not know how this happened but assuming its a just my fault running the converge ( or not ).

thank you for helping!

**Comment by sawanoboly** [comment]
@EugenMayer Thanks for your report.

Management of attributes is a difficult problem. It depends on the policy of each organization.

It seems that you need to change specific repository reference by node as you showed samples. In my case, such attributes are often defined in environments.

I think that this official document is quite helpful.

Https://docs.chef.io/attributes.html

**Comment by EugenMayer** [comment]
Environments are rather not node specific, are they. Think about a secario were you run several paas servers, each with own credentials for registry and other services. If you pick envs here you would create 1 env per paas instance, which does not really scale.

Or did i miss the point?

**Comment by sawanoboly** [comment]
I understand. 
It is certainly one of the right ways to use the attributes of a node if you need individual node values.
In addition, data_bag can be used as another method in this case.

**Comment by EugenMayer** [comment]
data_bags are probably, using a special folder layout + encryption something you can design to be node-centric, but it feels like its more designed to be non-node-centric ( global ) and node-specific settings seem to be rather not really practical
