### ISSUE TITLE
Integration test has been started crashing.

### ISSUE THREAD

**Issue by sawanoboly** [higanworks/knife-zero#118]
- https://circleci.com/gh/higanworks/knife-zero/tree/integration_testedge
  - https://circleci.com/gh/higanworks/knife-zero/7295

- related
  - https://github.com/chef/chef/pull/6471
  - https://github.com/chef/chef/commit/b89bbe9fced92791da5cd647490bb31d55ac49df

**Comment by EugenMayer** [comment]
@sawanoboly at this point please take the credit for your work. Its very valuable!

**Comment by sawanoboly** [comment]
resolved.
