### ISSUE TITLE
Getting ERROR 412 with Cookbooks that use Supermarket Cookbooks

### ISSUE THREAD

**Issue by darkn3rd** [higanworks/knife-zero#121]
If my cookbooks use a supermarket cookbook installed through Berksfile, then I get this error: `ERROR: 412 "Precondition Failed "`

### STEPS

```bash
chef gem install knife-zero
knife zero bootstrap tools.dev \
  --node-name tools.dev \
  --environment dev \
  --run-list 'recipe[dk_oracle_java::repo]' \
  --ssh-user vagrant \
  --sudo
```

My metadata.rb has `depends 'hostsfile', '~> 3.0.1'`.

So `berks install` creates:
```
DEPENDENCIES
  dk_oracle_java
    path: .
    metadata: true

GRAPH
  dk_oracle_java (0.1.0)
    hostsfile (~> 3.0.1)
  hostsfile (3.0.1)
```

### ACTUAL RESULTS

```
tools.dev -----> Existing Chef installation detected
tools.dev Starting the first Chef Client run...
tools.dev Starting Chef Client, version 13.8.5
tools.dev resolving cookbooks for run list: ["dk_oracle_java::repo"]
tools.dev 
tools.dev ================================================================================
tools.dev Error Resolving Cookbooks for Run List:
tools.dev ================================================================================
tools.dev 
tools.dev Missing Cookbooks:
tools.dev ------------------
tools.dev No such cookbook: hostsfile
tools.dev 
tools.dev Expanded Run List:
tools.dev ------------------
tools.dev * dk_oracle_java::repo
tools.dev 
tools.dev System Info:
tools.dev ------------
tools.dev chef_version=13.8.5
tools.dev platform=ubuntu
tools.dev platform_version=14.04
tools.dev ruby=ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux]
tools.dev program_name=chef-client worker: ppid=14192;start=17:59:41;
tools.dev executable=/opt/chef/bin/chef-client
tools.dev 
tools.dev 
tools.dev Running handlers:
tools.dev [2018-03-26T17:59:42+00:00] ERROR: Running exception handlers
tools.dev Running handlers complete
tools.dev [2018-03-26T17:59:42+00:00] ERROR: Exception handlers complete
tools.dev Chef Client failed. 0 resources updated in 01 seconds
tools.dev [2018-03-26T17:59:42+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
tools.dev [2018-03-26T17:59:42+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
tools.dev [2018-03-26T17:59:42+00:00] ERROR: 412 "Precondition Failed "
tools.dev [2018-03-26T17:59:42+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

### EXPECTED RESULTS

I was hoping that it would work, or if there were documentation around this.  

## CONFIGURATION

* Hosts: Ubuntu 16.04
    * Chef Development Kit Version: 2.3.5
Guest: Ubuntu 14.04

Running in vagrant environment with `~/.ssh/config` entry for `tools.dev`.  This works fine for any cookbooks that don't require any supermarket cookbooks.

**Comment by sawanoboly** [comment]
@darkn3rd 

Does cookbook_path contain the cookbooks path to install by berkshelf?

https://knife-zero.github.io/tips/with_cookbook_manager/

**Comment by darkn3rd** [comment]
This is in regards to the knife-zero tips article (great article btw). 

As a new person, I wouldn't be sure what to do with content.  Also, I would not be familiar with `berks vendor`.  Does the regular process using full Chef Server do this automatically?

The content is a snippet for the `knife.rb` or `chef.rb` snippet?   For this to work, one would have to craft a global `Berksfile` to include all the external cookbooks used in all the cookbooks?  Essentially:

```bash
cat <<-EOF > Berksfile
source 'https://supermarket.chef.io'

$(grep -Rh 'depends' cookbooks/* | sed 's/depends/cookbook/' | sort | uniq )
EOF
```

For `knife[:before_bootstrap]` and `knife[:before_converge]`, where is the starting directory (cwd) to run a command specified?

**Comment by darkn3rd** [comment]
Alright, I got this working with with script to fetch all cookbooks dependencies specified in metadata.rb, now works, confused by docs (newbie).  Does regular knife/chef-server process do this automatically?

```ruby
chef_repo = File.join(File.dirname(__FILE__), '../ninjapants-chef-repo')
site_cookbooks = "#{chef_repo}/cookbooks"
berks_cookbooks = "#{chef_repo}/berks-cookbooks"

chef_server_url "http://127.0.0.1:8889"
cookbook_path [site_cookbooks, berks_cookbooks]

# Knife Zero Configs
knife[:before_bootstrap] = "cd #{chef_repo} && ./global_berks_vendor"
knife[:before_converge] = "cd #{chef_repo} && ./global_berks_vendor"
```

**Comment by sawanoboly** [comment]
Berkshelf is one of the related tools of Chef, this may be an option. I think that you do not have to use it if you think it is confusing.

> Does regular knife / chef-server process do this automatically?

I think that this will not be done automatically. Please see the documentation of Berkshelf for details or ask the maintainer.

I'm going to close this Issue. Is that okay?

**Comment by darkn3rd** [comment]
I personally do not find it confusing, I was trying to say it is confusing as written (especially to new comers), and as Berkshelf is standardized by Chef (given `chef generate` command included with ChefDK), it might be worth adding docs or references to the README.  I am cool with closing this.

**Comment by sawanoboly** [comment]
Thank you for your opinion.
