### ISSUE TITLE
Use the node's ipaddress to open SSH connection instead of its hostname

### ISSUE THREAD

**Issue by zedtux** [higanworks/knife-zero#130]
I have nodes where I installed a VPN, and too easily identity them, I changed their hostname to something talking to me using the [hostname](https://supermarket.chef.io/cookbooks/hostname) cookbook.

Now when I try to converge a node, I have the error that the node cannot be reached at the given hostname, which is normal as there is no DNS entry for those names, excepted within the VPN where my machine is not connected to.

Instead of connecting to the host using its hostname, knife-zero should use its IP address.

You could think this is a chef issue, but actually, I don't think with chef and a chef server this would be an issue as the chef client is connecting to the chef server, not the way around, while for knife zero it's the _server_ (our machines) that connect to the node, so that's why I think this is a knife-zero issue.

**Comment by sawanoboly** [comment]
https://knife-zero.github.io/40_configuration/

`knife[:ssh_attribute] = "knife_zero.host"`

How about adding this setting to knife.rb?

**Comment by zedtux** [comment]
Thank you @sawanoboly for your answer.

What is doing this line?

**Comment by sawanoboly** [comment]
https://docs.chef.io/knife_ssh.html

Originally, Chef has a function to specify the attribute to be used for connection instead of the hostname.
Since knife-zero holds the ipaddress used at bootstrap time, it can be reused. Of course, it is also possible to use other attributes. You can select from the values stored in the node object (nodes / *. json).

**Comment by zedtux** [comment]
Oh I see. Thank you.

If I'm getting it right, `knife_zero.host` would use the IP address?

Where come from this `host`? 
I mean what are the other values that could be passed?

**Comment by sawanoboly** [comment]
> If I'm getting it right, knife_zero.host would use the IP address?

The value used for `knife zero bootstrap`.  I do not know because it depends on the your environment.
It may be an IP address, or it may be a reachable host name from the Workstation you have run.

> I mean what are the other values that could be passed?

For example, node has the attribute `ipaddress`. There are more, so please look at the file.
It depends on the environment, but there are probably some that can be used.

**Comment by zedtux** [comment]
Unfortunately it doesn't seem to work for me:

```
$ knife zero diagnose
...
Zero Converge Config
====================
---
:concurrency:
:manual: false
:ssh_password_ng: false
:ssh_timeout: 120
:host_key_verify: true
:on_error: false
:duplicated_fqdns: :fatal
:tmux_split: false
:remote_chef_zero_port:
:use_sudo: true
:override_runlist:
:client_version:
:ssh_attribute: knife_zero.host
...
```

But when I converge the host:

```
...
WARNING: Failed to connect to dev-k8s-master-1.domain.com -- SocketError: getaddrinfo: Name does not resolve
ERROR: NoMethodErrorundefined method `forward' for nil:NilClass
ERROR: /usr/local/bundle/gems/knife-zero-2.0.3/lib/knife-zero/bootstrap_ssh.rb:30:in `block in ssh_command'
...
```

I have the same issue when having `knife[:ssh_attribute] = "knife_zero.ipaddress"` in my `knife.rb` file.

**Comment by sawanoboly** [comment]
`./nodes/dev-k8s-master-1.domain.com.json`

Does `./nodes/dev-k8s-master-1.domain.com.jso` contain a description of the IP address you want to use?

**Comment by zedtux** [comment]
That what I was looking at and no there is no attributes with the IP address, which is really weird.

**Comment by zedtux** [comment]
Here is my `knife.rb` file:

```
chef_repo_path              File.expand_path('../' , __FILE__)
local_mode                  true
policy_document_native_api  false
use_policyfile              true
versioned_cookbooks         true

## use specific key file to connect server instead of ssh_agent(use ssh_agent is set true by default).
# knife[:identity_file] = "~/.ssh/id_rsa"

# Use host IP address instead of FQDN to connect via SSH?
knife[:ssh_attribute] = 'knife_zero.host'

## Attributes of node objects will be saved to json file.
## the automatic_attribute_whitelist option limits the attributes to be saved.
knife[:automatic_attribute_whitelist] = %w[
  fqdn
  os
  os_version
  hostname
  ipaddress
  roles
  recipes
  ipaddress
  platform
  platform_version
  cloud
  cloud_v2
  chef_packages
]
```

**Comment by zedtux** [comment]
Okay so you guided me well, it is now working, I don't know how I messed up my node files, but now it's working and I see what parts of the JSON file makes the _magic_:

```json
{
  "name": "dev-k8s-master-1",
  "chef_environment": "staging",
  "normal": {
    "knife_zero": {
      "host": "1.2.3.4"
    },
}
```
