### ISSUE TITLE
Encrypted data bags supported by knife-zero?

### ISSUE THREAD

**Issue by leoc** [higanworks/knife-zero#141]
Hello, thank you a lot for knife-zero!

It works like a charm. I have only one question. How would you use encrypted data bags for secret information? When running `diverge` chef is complaining about missing secrets. Would it be possible to only transfer the data bag items my recipes are using on that node?

**Comment by sawanoboly** [comment]
Would you give me some more details ? For example, configuration, error and warning message details.

Normally, encrypted data bag items are only used for decryption in recipes, so if you don't include them in node's run list, it won't end up with an error.

**Comment by leoc** [comment]
Thank you for your quick response and sorry that I forgot an example.

I am using currently trying to access a data bag item in my recipe
`cookbooks/app/recipes/app01.rb` via:

```
puts data_bag_item('app-config', id).inspect * 100
```
And I get the following error:

```
192.168.23.70   ==============================================================================
192.168.23.70   Recipe Compile Error in /var/chef/cache/cookbooks/app/recipes/app01.rb
192.168.23.70   ================================================================================
192.168.23.70   
192.168.23.70   ArgumentError
192.168.23.70   -------------
192.168.23.70   No secret specified and no secret found at /etc/chef/encrypted_data_bag_secret
192.168.23.70   
192.168.23.70   Cookbook Trace:
192.168.23.70   ---------------
192.168.23.70     /var/chef/cache/cookbooks/app/recipes/app01.rb:58:in `block in from_file'
192.168.23.70     /var/chef/cache/cookbooks/app/recipes/app01.rb:55:in `each'
192.168.23.70     /var/chef/cache/cookbooks/app/recipes/app01.rb:55:in `from_file'
192.168.23.70   
192.168.23.70   Relevant File Content:
192.168.23.70   ----------------------
192.168.23.70   /var/chef/cache/cookbooks/app/recipes/app01.rb:
192.168.23.70   
192.168.23.70    56:    id = instance_config[:identifier]
192.168.23.70    57:  
192.168.23.70    58>>   puts data_bag_item('app-config', id).inspect * 100
192.168.23.70    59:  
192.168.23.70    60:    config = default_config
192.168.23.70    61:               .merge(
192.168.23.70    62:                 db_name: "#{id}_production",
192.168.23.70   
192.168.23.70   System Info:
192.168.23.70   ------------
192.168.23.70   chef_version=15.8.23
192.168.23.70   platform=debian
192.168.23.70   platform_version=10
192.168.23.70   ruby=ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]
192.168.23.70   program_name=/usr/bin/chef-client
192.168.23.70   executable=/opt/chef/bin/chef-client
```

I am using the `knife[:secret_file]` configuration in my `knife.rb`.

Maybe I am missing something.

**Comment by sawanoboly** [comment]
Ah, understood.

This is what happens if you encrypt your databag after bootstrapping. The remote node also needs a secret key file.

Please execute `knife zero bootstrap` again with the setting `knife[:secret_file]`.
When you run bootstrap again with the `--no-converge` option, you can overwrite only the settings on the remote node without running the recipe.

**Comment by sawanoboly** [comment]
@leoc any updates?

I'll close this at next week.

**Comment by leoc** [comment]
Thank you very much! Everything works as expected! Have a wonderful day :+1:
