### ISSUE TITLE
How to update chef-client on the remote host?

### ISSUE THREAD

**Issue by leoc** [higanworks/knife-zero#142]
Hey there, I am using chef-zero a lot and it works perfectly. So thank you a lot.

One question though. How would I keep the chef-client up-to-date on my machines or lock the chef version? Right now I have 15.8 the older hosts and 16.0 on my new hosts. Now I have the issue that older LWRP resources are named directly but with 16.0 resources include the cookbook name as a prefix. How do you update your older machines?

Thanks :)

**Comment by sawanoboly** [comment]
There are several ways to do this.

- Using the `zero converge` with the `--client-version` option.
  - Ref: https://knife-zero.github.io/30_subcommands/#converge
- Run the `zero bootstrap` again with the `--no-converge` option.
  - Ref: https://knife-zero.github.io/30_subcommands/#bootstrap
- Run the installer with `knife ssh`.
  - Ref:  https://docs.chef.io/workstation/knife_ssh/

Either way, you can specify a version.

**Comment by leoc** [comment]
Thank you for your quick reply.

So there is no default chef version that I could specify in my knife.rb config.
I would like to avoid installing latest chef-client automatically.

For now I will use the `--client-version` but something automatic would be nice :-)

![](https://media0.giphy.com/media/3oz8xIsloV7zOmt81G/giphy.gif)

**Comment by sawanoboly** [comment]
You can specify only the chef version in `knife.rb` for bootstrapping.
for example,

```
knife[:bootstrap_version] = '16.1.16'
```

**Comment by leoc** [comment]
That's exactly what I was looking for, thanks!

Sorry I did not look for the knife related config: https://docs.chef.io/workstation/config_rb/#optional-settings

![](https://media2.giphy.com/media/6tHy8UAbv3zgs/giphy.gif)
