### ISSUE TITLE
Chef 16系でcincがうまく動かない

### ISSUE THREAD

**Issue by pyama86** [higanworks/knife-zero#159]
cinc version 16.12.3

knife.rb
```ruby
knife[:client_version] = '16.12.3'
knife[:alter_project] = 'cinc'
```
下記のようなコマンドではうまくcincが入らず、
```
$ knife zero bootstrap ${YOUR_NODE_IP} \
  --sudo \
  --alter-project cinc \
  -N my-ubuntu16 \
  --no-converge
```

```
--bootstrap-url https://omnitruck.cinc.sh/install.sh 
```
を明示的に引数に与えないと動作しなかった。
https://github.com/higanworks/knife-zero/blob/main/lib/knife-zero/bootstrap_ssh.rb#L46
がコールされてない感じがある。

また、インストール後も、
convergeすると、

```
Private Key Not Found:
----------------------
Your private key could not be loaded. If the key file exists, ensure that it is
readable by Cinc Client.

Relevant Config Settings:
-------------------------
validation_key "/etc/cinc/validation.pem"
```

のようなエラーで正常に動きませんでした。

```
knife[:validation_key] = nil 
```
を設定に書き足してみるも効果がなさそうで、16系だとなにか動作が違ったりするのかなぁと思って調べている。

**Comment by pyama86** [comment]
```
bundle exec knife ssh --attribute ipaddress 'name:xxxx' 'sudo dpkg -r chef'
bundle exec knife zero bootstrap  --sudo xxxx --node-name xxxx \
  --alter-project cinc --no-converge \
  --bootstrap-url https://omnitruck.cinc.sh/install.sh
bundle exec knife ssh --attribute ipaddress 'name:xxx'
```
僕のケースだとchefからの移行なのでなにか特殊かもしれませんが、とりあえず上記で動きました！

**Comment by sawanoboly** [comment]
フィードバックありがとうございます！ 該当箇所を見直してみますー

**Comment by pyama86** [comment]
あと、 `knife[:client_version] ` を入れてると、convergeのたびに、cincのダウンロードしちゃうっぽくて、バージョン取得がうまくできないとかそういうのも関連であるかもしれません。

**Comment by sawanoboly** [comment]
bootstrap urlは下記への書き換えでよさそうでした。

```
@config[:bootstrap_url] = 'https://omnitruck.cinc.sh/install.sh'
```

ほか、ちょっとややこしいですが bootstrap時のバージョン指定はパラメータ別になっています。

```
knife[:bootstrap_version] = '16.12.3'
```


次バージョンで対応します。

**Comment by pyama86** [comment]
ははぁ、なるほど。

**Comment by sawanoboly** [comment]
> あと、 knife[:client_version] を入れてると、convergeのたびに、cincのダウンロードしちゃう

`client_version` は更新用のオプションなので、一応現状としてはそういう仕様になっちゃいます。

基本的に `bootstrap_version` で指定バージョンをインストールしつつ、一斉更新の際などに client_version を使うという運用でどうでしょうか。

**Comment by sawanoboly** [comment]
とりいそぎ、bootstrap時に alter_project で bootstrap_urlが別途指定が必要だった件を修正した 2.4.1をリリースしましたー

**Comment by sawanoboly** [comment]
client_version オプションがあるときの挙動は、下記のようにかなり強引に処理を突っ込んでいるため、現行のバージョンとかみておらんのです。

https://github.com/higanworks/knife-zero/blob/main/lib/knife-zero/bootstrap_ssh.rb#L47-L54

見るようにしてもいいのかなー。

**Comment by sawanoboly** [comment]
ローカルの`nodes/` にあるchef_packages を比較対象にすればスキップできるかもしれませんね。

**Comment by sawanoboly** [comment]
あ、rubyに渡してるワンライナー内で頑張って Chef::Version と比較しちゃえばいいのか。

**Comment by sawanoboly** [comment]
```
/opt/cinc/embedded/bin/ruby -rchef -ropen-uri -e 'if Chef::VERSION == "16.12.3" ; puts "/bin/true" ; else ; puts open("https://omnitruck.cinc.sh/install.sh").read ; end' | sh -s -- -v 16.12.3
```

こうかー。 なんかひどいw

**Comment by pyama86** [comment]
> 基本的に bootstrap_version で指定バージョンをインストールしつつ、一斉更新の際などに client_version を使うという運用でどうでしょうか。

よさそうです！

**Comment by pyama86** [comment]
とりあえず、knife.rbにchefのバージョン定義せずに必要なときに引数で渡せば良さそうってのがわかったから、都度インストールされちゃう問題は大丈夫そうです。

**Comment by sawanoboly** [comment]
諒解です！ 2.5.xに上げるころにもしかしたらバージョンチェックも入れるかもです。

このIssueはCloseでよいですか？
