### ISSUE TITLE
Chef dependency should be >= 17 for 2.4.x

### ISSUE THREAD

**Issue by EugenMayer** [higanworks/knife-zero#161]
due to knife 17 being a requirement for 2.4.x, it requires chef >= 17 itself. 
We still have chef >= 15 in knife-zero though and should adjust that (it can no longer run with anything below 17).

**Comment by sawanoboly** [comment]
Once I have detailed usage information, I can figure out what to do.

However, if you want to continue to use Chef 16 or lower on your WorkStation, you can continue to use Knife-Zero 2.3.x.
As mentioned in the changelog, there are no major feature additions in 2.4.x. The main change is the support for Chef17.

https://github.com/higanworks/knife-zero/blob/main/CHANGELOG.md
