### ISSUE TITLE
knife zero converge command got  sudo: chef-client: command not found error

### ISSUE THREAD

**Issue by chadjiang** [higanworks/knife-zero#164]
I use knife zero to provision Apple M1 mini mac on macstadium. 

When I ran knife zero bootstrap with run-list , it is working and run receipts in run-list. And chef-client was installed in the node, the path is **/opt/chef/bin/chef-client** . 

after that, if i ran **knife zero converge**  then i got error:  **sudo: chef-client: command not found**.

When I logged in the node,  and ran **sudo chef-client**   , then I will get this error:

administrator@45178 bin % sudo chef-client
Chef Infra Client, version 17.9.18
Patents: https://www.chef.io/patents
Infra Phase starting

Unexpected Error:
-----------------
ChefZero::ServerNotFound: No socketless Chef Zero server on given port 8889

System Info:
------------
chef_version=17.9.18
ruby=ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [arm64-darwin20]
program_name=/usr/local/bin/chef-client
executable=/opt/chef/bin/chef-client

Running handlers:
[2021-12-29T23:42:43-08:00] ERROR: Running exception handlers
Running handlers complete
[2021-12-29T23:42:43-08:00] ERROR: Exception handlers complete
Infra Phase failed. 0 resources updated in 03 seconds
[2021-12-29T23:42:44-08:00] WARN: Error while reporting run start to Data Collector. URL: chefzero://localhost:8889/data-collector Exception: No HTTP Code -- No socketless Chef Zero server on given port 8889 
[2021-12-29T23:42:44-08:00] WARN: Error while reporting run start to Data Collector. URL: chefzero://localhost:8889/data-collector Exception: No HTTP Code -- No socketless Chef Zero server on given port 8889 
[2021-12-29T23:42:44-08:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2021-12-29T23:42:44-08:00] FATAL: ---------------------------------------------------------------------------------------
[2021-12-29T23:42:44-08:00] FATAL: PLEASE PROVIDE THE CONTENTS OF THE stacktrace.out FILE (above) IF YOU FILE A BUG REPORT
[2021-12-29T23:42:44-08:00] FATAL: ---------------------------------------------------------------------------------------
[2021-12-29T23:42:44-08:00] FATAL: ChefZero::ServerNotFound: No socketless Chef Zero server on given port 8889

How to fix this? 

Thank you!

**Comment by sawanoboly** [comment]
@chadjiang 

https://github.com/higanworks/knife-zero/issues/148#issuecomment-930780311

Try running it on a mac with the settings shown in this issue comment.

**Comment by chadjiang** [comment]
i added Chef::Config[:chef_client_path] = "/usr/local/bin/chef-client"  in knife.rb , but not working.  Chef just updated their chef version to  17.9.18.  Do you know which chef infra version  **knife zero** support? I would like to downgrade chef infra client to that version to try?  

When I use chef server to mange node, I did not see this kind of issue.   I guess something possible related to ChefZero when we do **knife zero bootstrap**

**Comment by sawanoboly** [comment]
I guess I didn't explain well enough. Try putting the following path in `knife.rb` according to your environment.

```
Chef::Config[:chef_client_path] = "/opt/chef/bin/chef-client"
```

**Comment by chadjiang** [comment]
I tried this, but did not work either. 

after use **knife zero bootstrap**  , knife zero converge did not work and get this error: 
sudo: chef-client: command not found

and knife ssh got failed 
`knife ssh  "name:mac-chef-test-m1" 'sudo /opt/chef/bin/chef-client'`
it throw same errors as ran "chef-client" directly in the node. 

When I checked client.rb 
chef_server_url  "chefzero://localhost:8889"
chef_zero.port 8889
I think for some reason chefzero on localhost 8889 not working, which cause failure.

**Comment by chadjiang** [comment]
I followed this https://github.com/higanworks/knife-zero/issues/148#issuecomment-842707690  to create .zshenv add  `/usr/local/bin` into PATH in the node,  then **knife zero converge**  working!   Thank you very much!

**Comment by sawanoboly** [comment]
@chadjiang 
 I'm glad to hear that it was resolved. I will pass on some additional information.

Let me explain how knife-zero works.
At runtime, knife-zero starts a chef-zero server on the local node, and the remote node gets the recipe via ssh port forward.
The chef-zero server is not started all the time, but is only running when knife-zero is running. Therefore, it is the correct behavior that chef-zero is not running on the remote node.
