### ISSUE TITLE
knife zero converge - sudo: chef-client: command not found

### ISSUE THREAD

**Issue by joshedney** [higanworks/knife-zero#165]
Hey,

I've got an issue where after bootstrapping a node, I am unable to run `knife zero converge`

On the remote node, if I run `which chef-client` I get back `/usr/local/bin/chef-client`

However if I run it via `knife ssh "name:*" "which chef-client"` I get `chef-client not found`

Running `knife ssh "name:*" "cat /etc/paths"` it is showing up as including the above path.
` /usr/local/bin
 /usr/bin
 /bin
 /usr/sbin
 /sbin
 /usr/loca/bin`

Any ideas? 

Workstation Versions:
MacOs 11.0.1
Chef Workstation version: 22.1.745
Chef Infra Client version: 17.9.26
Chef InSpec version: 4.52.9
Chef CLI version: 5.5.0
Chef Habitat version: 1.6.420
Test Kitchen version: 3.2.2
Cookstyle version: 7.26.1

Node Versions:
Chef Infra Client: 17.9.26

**Comment by sawanoboly** [comment]
When the remote node defaults to zsh, you may need to add a few settings.
Please refer to the comments below and try again.

https://github.com/higanworks/knife-zero/issues/148#issuecomment-842707690
