### ISSUE TITLE
is it possible to integrate with berkshelf so we don't have to pull site-cookbooks manually

### ISSUE THREAD

**Issue by chrisduong** [higanworks/knife-zero#21]
Hi,

I'm suggesting that we  could use Berkshelf to download all dependency cookbooks so we can make wrapper cookbook for knife zero easier, without worrying about putting correct site cookbook version.
Thanks

**Comment by sawanoboly** [comment]
Hi, Thank you for your feedback.
I don't like to making integration or dependency other than chef-core.

The feature which you suggested should implements by the chef-zero.
Could you try to request as the chef-zero's issue?

https://github.com/chef/chef-zero

**Comment by chrisduong** [comment]
I think It is fair enough. Thanks for answering, I close the ticket here.
