### ISSUE TITLE
Aboid [Doing old-style registration]

### ISSUE THREAD

**Issue by sawanoboly** [higanworks/knife-zero#24]
Chef12 integrates with chef-vault.

**Comment by sawanoboly** [comment]
valut suppot. v1.5.0

**Comment by allaire** [comment]
How can we get rid of:

```
Doing old-style registration with the validation key at ...ix.com --ssh-user ...
Delete your validation key in order to use your user credentials instead
```

**Comment by sawanoboly** [comment]
@allaire Don't worry about it.

This warning message is not effect Knife-Zero's behavior. Because authrization of Chef-Zero is dummy.

And if you want to know about this, please see below article.

- https://www.chef.io/blog/2015/04/16/validatorless-bootstraps/

Next, we can rid this warning by using chef-vault when bootstraping if we want.

- https://www.chef.io/blog/2013/09/19/managing-secrets-with-chef-vault/
