### ISSUE TITLE
Rename/alias `knife zero chef_client` command

### ISSUE THREAD

**Issue by patcon** [higanworks/knife-zero#32]
Firstly, amazing great project! So glad it exists, and migrating from chef-solo/knife-solo now.

So yeah, wondering whether another command would be more intuitive, as I didn't realize what the `knife zero chef_client QUERY` command meant until my second attempt to sort out this plugin :)

I might suggest `knife zero converge QUERY`, which takes a note from `test-kitchen` terminology, which many folks know. It's also less alienating for those coming from chef-solo, who might not even really care that chef-client is being run remotely, and are just thinking "I've heard chef-zero is the replacement for chef-solo" (I'll admit this was my mental model, having migrated my test-kitchen and vagrant setups to chef-zero in ignorance, as those tools conveniently hide the complexity of the change)

**Comment by sawanoboly** [comment]
Thanks, Test-kitchen is one of my favorite oss (maybe I like than Chef).
When I thought about name of convergence step, I was debating between `chef_client` and `converge`.
Then I decided name to `chef_client` because command which is executed on remote node is chef-client. 

But, I'll try to think about alias.

**Comment by patcon** [comment]
Thanks for considering @sawanoboly!

**Comment by sawanoboly** [comment]
@patcon 
I'd try to make alias `converge` to `chef_client`. How about https://github.com/higanworks/knife-zero/commit/8f33e8912f6dc8edf098a7b66b58544ba2f339dc ?

**Comment by patcon** [comment]
Looks awesome! I'll start using that branch.

**Comment by sawanoboly** [comment]
Released as v1.6.0.
