### ISSUE TITLE
Make knife-zero play nice with ssh config files

### ISSUE THREAD

**Issue by patcon** [higanworks/knife-zero#34]
Doing this results in failure:

```
~/blendive/kitchens/project-kitchen (feature/knife-zero ✘)✹✭ ᐅ vagrant ssh-config >> ~/.ssh/config
~/blendive/kitchens/project-kitchen (feature/knife-zero ✘)✹✭ ᐅ knife zero chef_client name:knife-zero-test
WARNING: Failed to connect to knife-zero-test -- Net::SSH::AuthenticationFailed: Authentication failed for user root@127.0.0.1@knife-zero-test
ERROR: NoMethodErrorundefined method `forward' for nil:NilClass
ERROR: /home/patcon/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/knife-zero-1.5.0/lib/knife-zero/bootstrap_ssh.rb:22:in `block in ssh_command'
/home/patcon/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/knife-zero-1.5.0/lib/knife-zero/bootstrap_ssh.rb:20:in `each'
/home/patcon/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/knife-zero-1.5.0/lib/knife-zero/bootstrap_ssh.rb:20:in `ssh_command'
/home/patcon/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/chef-12.3.0/lib/chef/knife/ssh.rb:526:in `run'
```

It would seem to make sense if knife recognized the user in the ssh config setting, and used it as the `--ssh-user` if not explicitly overridden with flag usage.

Let me know your thoughts and I can investigate what's needed :)

**Comment by patcon** [comment]
Seems like this comes from either net-ssh-multi or net-ssh-gateway not knowing about net-ssh's ability to parse ssh_config files:
https://net-ssh.github.io/ssh/v2/api/classes/Net/SSH/Config.html

**Comment by patcon** [comment]
Sample of how knife properly deals with ssh_config by default:
https://github.com/chef/chef/blob/d8172e646d9fbf43e57bca5e20d0ac352ba9a66a/lib/chef/knife/ssh.rb#L213

**Comment by patcon** [comment]
Hm. I see that that's done for bootstrap, but I think there's some confusion, as Net::SSH.configuration_for returns a hash with a `:user` and `:port` key, and it appears the current code assumes it would be at `:ssh_user` and `:ssh_port`

I unfortunately don't have time to sort this out for my current project, but I'll try to come back later and submit a PR :)

**Comment by patcon** [comment]
Also, any reason bootstrap and chef_client subcommands couldn't share more ssh config info?

**Comment by sawanoboly** [comment]
Thank you for your report, It's a bug.
I want to fix it if possible.

**Comment by sawanoboly** [comment]
> I see that that's done for bootstrap, but I think there's some confusion, as Net::SSH.configuration_for returns a hash with a :user and :port key, and it appears the current code assumes it would be at :ssh_user and :ssh_port

Ahh.. That makes sense!

**Comment by sawanoboly** [comment]
I noticed that I have to change ssh_user 'root' to nil by default. hmm...

**Comment by sawanoboly** [comment]
Related(loose) : https://github.com/chef/chef/pull/4038

**Comment by sawanoboly** [comment]
@patcon 
Maybe this issue will be solved with... 

- knife-zero-1.9.0.pre.1
    - remove default ssh_user.
- chef 12.5 (not released yet)
    - load ssh config file at `Chef::Knife::SSH#session_options`

**Comment by sawanoboly** [comment]
chef 12.5 and knife-zeto 1.9.0 has released. close for now. 

And hand over baton to #48
