### ISSUE TITLE
Allow node object to be used during bootstrap (particularly run_list)

### ISSUE THREAD

**Issue by patcon** [higanworks/knife-zero#36]
I can think of two options that would not tread on what `knife bootstrap` already do:

1. Parse the `node/#{fqdn}.json` for the run-list and programmatically add it as default to `option :first_boot_attributes`
2. Use something like `net-scp` to send over the node object, and run against that file rather than the default empty one that chef comes with: https://github.com/higanworks/knife-zero/blob/e4a3131f9ab38faa5c7a5ca6ffdcb1403d35c25e/lib/knife-zero/core/bootstrap_context.rb#L22

**Comment by sawanoboly** [comment]
https://github.com/chef/chef/pull/3459

**Comment by patcon** [comment]
You are awesome.
