### ISSUE TITLE
Allow customization of node's client.rb via bootstrap_context

### ISSUE THREAD

**Issue by patcon** [higanworks/knife-zero#39]
Certain automatic node attributes change between every node save (memory, interface stats, etc.). For those who are committing the json node objects into version control, it would be nice to allow this noise to be disabled.

We can do that here, where the client.rb template is generated during bootstrap, by adding a key for ["whitelisted attributes"](/dev/mapper/packer):
https://github.com/chef/chef/blob/d8172e646d9fbf43e57bca5e20d0ac352ba9a66a/lib/chef/knife/core/bootstrap_context.rb#L64-L69

We can append `automatic_attribute_whitelist []` to the bootstrapped node's `client.rb` to completely silence the noisy automatic attributes, but that's likely too opinionated. Most stay constant anyhow.

We could instead allow arbitrarily adding key-value pairs to the generated client.rb. Or alternatively, we could have a more user-friendly config that adds something like this, which should silence most noise:

```rb
# client.rb snippet
automatic_attribute_whitelist %w(
  !network/interfaces
  !memory/
]
```

Blacklisting seems to be an undocumented feature...
https://github.com/chef/chef/blob/59da09f64b72dbd712c890f999322493a4bc9ec4/lib/chef/node_map.rb#L157

EDIT: Turns out blacklisting isn't a thing, so this isn't useful for now

**Comment by patcon** [comment]
fwiw, it seems `automatic_attribute_whitelist` needs at least `["fqdn/"]` in order for `knife-zero` to continue to work. But this is probably a minimum, so that the `knife node show NAME` is still maximally populated:

```rb
# client.rb
automatic_attribute_whitelist [
  "fqdn/",
  "ipaddress/",
  "roles/",
  "recipes/",
  "ipaddress/",
  "platform/",
  "platform_version/",
]
```

**Comment by patcon** [comment]
Oh hey, this can be done here:
https://github.com/opscode-cookbooks/chef-client

But hey, I'll leave this open in case you want to have a simple flag in knife.rb that quiets down all the noisy linux automatic attrs.

**Comment by sawanoboly** [comment]
I see. Thank you for good report of use case!

**Comment by sawanoboly** [comment]
Note: I've catched up similar feedback from twitter. https://twitter.com/masudaK/status/608555090165776384

**Comment by sawanoboly** [comment]
https://github.com/chef/chef/blob/59da09f64b72dbd712c890f999322493a4bc9ec4/lib/chef/knife/core/bootstrap_context.rb#L64

`client.rb` is made by `.config_content` .  I'm going to append content by around_alias.

Which do you think is better? @patcon @rmoriz

- be able to append free format content to client.rb.
- create new option such as `--[no-]suppress-attributes` for add whitelist automatically.
- create new options such as --attribute_whitelist, attribute_blacklist as Array.

**Comment by sawanoboly** [comment]
hmm...   how about #43 ?

**Comment by patcon** [comment]
Hm. I realize I made the request, but I'd actually moved away from the idea of using the whitelist (unless they add negating and make a blacklist possible). So much node information seems to be lost unless the whitelist is VERY extensive, which strikes me as very hard to manage (different platforms have different top-level keys for automatic attrs, etc.)

Perhaps this is best implemented as a recommended wrapper cookbook around one of the blacklist attrs cookbooks mentioned in https://github.com/chef/chef/issues/3533?

**Comment by patcon** [comment]
I'm going to close this for now, as you've created a feature that addresses the initial request, and my new preferred way approach will be done outside this project :)

**Comment by rmoriz** [comment]
(Let me just add my notes, which may help other people having the same issue: 

I was manging the node.json files manually (coming from a knife-solo setup) and initially had the same issue until I found out, that `knife node edit <name>` removes a lot of the clutter before opening the editor. This fits my use case, as I'm happy to store everything in git.)

**Comment by sawanoboly** [comment]
@patcon 
Thanks, I also seemed blacklist approach is better. ( discussed in https://github.com/chef/chef/issues/3533 )

Apart from that,  I thought also likely case useful to append whitelist, so I implemented it.

**Comment by sawanoboly** [comment]
@rmoriz Yes, It's kind of use case :smiley:

**Comment by patcon** [comment]
Rockin :)

And thanks @rmoriz! That's actually really helpful for our workflow! I hadn't put two and two together on that
