### ISSUE TITLE
[The goal] zero commands implement into core.

### ISSUE THREAD

**Issue by sawanoboly** [higanworks/knife-zero#41]
T/O

**Comment by patcon** [comment]
Core moves more slowly than the plugin space, in my experience. fwiw, I would much rather have an active plugin ecosystem than see chef-core swallow up all the interesting projects and then have a smaller developer base keeping up with PRs :)

Integration into core would be a step backward imho.

**Comment by sawanoboly** [comment]
Don't worry. For the time being, I have no plans.
