### ISSUE TITLE
Tighter berkshelf integration

### ISSUE THREAD

**Issue by patcon** [higanworks/knife-zero#45]
I currently have a step in my projects where `berks vendor cookbooks` must be run in order to generate the cookbooks_path for the chef repo. I could imagine this leading to confusion if the Berksfile is updated, but the cookbook path is not re-vendored. Might be nice if this happened automatically (as knife-solo does). We could steal the code from knife-solo :)

**Comment by sawanoboly** [comment]
I think that the feature should be supported by chef-zero.  #21 (And I don't like Berkshelf very much.)
Then, A workflow based on Berkshelf  will be replaced by [Policyfile](https://docs.chef.io/config_rb_policyfile.html).

But, If you implement it and create PR, I can merge it.

**Comment by sawanoboly** [comment]
@patcon 
BTW, what do you think about librarian-chef ? I often use it. 
It has much less depends on other gems than Berkshelf depends on.

**Comment by daften** [comment]
I think both should be supported properly actually. I use berkshelf myself, but librarian-chef has a lot of users as well.

**Comment by sawanoboly** [comment]
F.Y.I

Librarian could relatively tighter integration with knife.

https://knife-zero.github.io/tips/with_cookbook_manager/

This setting checks Cheffile and Cheffile.lock before knife command running to avoid unintended behavior.

**Comment by patcon** [comment]
Just realized I never answered the original question on librarian-chef:

I always liked librarian much much more than berkshelf, but the lead developer seems to have been hired by facebook and disappeared from the FOSS community. He unfortunately hadn't been pushing librarian features as much as the berkshelf folks were. Librarian strikes me as the better-designed tool that is no longer maintained.

**Comment by sawanoboly** [comment]
@patcon 

I found little hack for tighter integration.
in `knife.rb`

```
## knife.rb will be read twice at run. (before launch chef-zero locally and before run knife.)
## And configuration for chef-zero doesn't has key `color`.
if ARGV[0..1] == ["zero", "converge"] && ! Chef::Config.has_key?(:color)
  system('bundle exec berks vendor')
end
```

And I have a cheap idea for integrate with other tools. That is adding option `zero.before_command` to add hook before connect via ssh. How do you feel about it?

**Comment by patcon** [comment]
That seems nifty :) I'm hiding knife-zero in rake tasks anyhow, so I've got this solved as far as I need it, but I'm sure newcomers would appreciate the before_command feature!

**Comment by sawanoboly** [comment]
I've added hooks  `before_bootstrap` and `before_converge` to run any command before the chef-client running. v1.11.1
It probably can be make tighter integration with cookbook managers.

http://knife-zero.github.io/tips/with_cookbook_manager/

How do you think ? I'm going to close this issue as resolve.

**Comment by patcon** [comment]
Ah, this looks really cool @sawanoboly :) I've got a tooling that works for me now, so I'll probably stick with that, but I think your solution will be perfect for the next person

**Comment by dfang** [comment]
@sawanoboly 

Hi, why knife-zero depends on chef 12.6.0( `spec.add_runtime_dependency "chef", "~> 12.6.0"` in gemspec), the latest version chef embedded in chefdk is 12.5.1, in order to run knife converge, i need to change 12.6.0 to 12.5.1 on my local.

`before_bootstrap` and `before_converge` hooks released in chef 12.6.0 ?

thanks !

**Comment by sawanoboly** [comment]
@dfang Ah.. this dependency need to support #37 . And, I came up with idea of before_hooks after implement it.

Please wait chef-dk :pensive: . Or, try to install new gems by bundler.

**Comment by dfang** [comment]
@sawanoboly How to replace chef 12.5.1 in chefdk with chef 12.6.0, chef gem install chef -v 12.6.0 seems not work.

thanks !

**Comment by sawanoboly** [comment]
@dfang 
I have workaround for it. But don't reccomend strongly.

```
$ cd your_chef_repo/
$ /opt/chefdk/embedded/bin/bundle init
$ echo "gem 'knife-zero'" >> Gemfile 
$ /opt/chefdk/embedded/bin/bundle install --binstubs --path=vendor/bundle


$ export PATH=/opt/chefdk/embedded/bin:$PATH
$ /opt/chefdk/embedded/bin/bundle exec knife -v
=> Chef: 12.6.0

$ /opt/chefdk/embedded/bin/bundle list knife-zero
=> /root/chefdk/work/vendor/bundle/ruby/2.1.0/gems/knife-zero-1.12.0

$ knife -v
=> Chef: 12.5.1
```

It's just first aid, please return to using chef-dk when new version released.
