### ISSUE TITLE
nodes/ folder - documentation

### ISSUE THREAD

**Issue by mrjcleaver** [higanworks/knife-zero#47]
Just want to check as the documentation doesn't mention it

I'm wondering about that nodes/ folder - can I consider it read only, just reflecting ohai data?

This feels different to how Chef Server works where I could edit a node's runlist in the Nodes tab.

Thanks, M.

**Comment by sawanoboly** [comment]
Please try edit files in `nodes/` to update run_list directly.
It will be kept after converge. 

Is this the kind of thing that you wanted to know?

**Comment by sawanoboly** [comment]
F.Y.I http://docs.chef.io/nodes.html#node-objects

There are no difference between chef-server's node and nodes/ folder.

**Comment by patcon** [comment]
We can do it martin, but the node object is very noisy and edits makes environments less reproducible, so I made efforts to make it unnecessary to edit it. I would consider changes made at the node level an anti-pattern that we should avoid if possible

**Comment by patcon** [comment]
But if we need to, best to use `knife node edit example.com`, and make changes only at "normal" level of precendence (that command filters out the other precendence levels for clarity. But again, I'm currently considering this an anti-pattern

**Comment by sawanoboly** [comment]
Thank you for detailed teaching @patcon . It had been optimistic that when he try it, he will know.

**Comment by patcon** [comment]
Maybe we could start a wiki on this repo with recommendations as we figure out best practices?

Also, I'm planning to use [`knife-skeleton`](https://github.com/Numergy/knife-skeleton) (with [this feature PR](https://github.com/Numergy/knife-skeleton/issues/5)) to make a skeleton of our starter chef-repo for starting projects. Might be something helpful for us all to collaborate on :)

(To clarify, I am contracting with @mrjcleaver, but it could be done on my own time too, depending on how he feels about it)

**Comment by sawanoboly** [comment]
@patcon 
You probably noticed that I don't have English force enough, So if I make some mistakes and delays , please be patient.

I had been writing usage on my blog or others, But it's written in Japanese :sweat: 
I agree with stating create document at wiki or github pages (such like the knife-solo, the Serverspec).
Then, would you mind if I added you to collaborators for this Repo or documentation Repo?

**Comment by patcon** [comment]
Yes, please do :)

**Comment by sawanoboly** [comment]
@patcon  I've created new issue https://github.com/higanworks/knife-zero/issues/49 .

@mrjcleaver Could I close this ( #47 ) issue ?

**Comment by sawanoboly** [comment]
http://knife-zero.github.io/20_getting_started/
