### ISSUE TITLE
No winrm support

### ISSUE THREAD

**Issue by djmbm** [higanworks/knife-zero#51]
Missing winrm support.

My normal bootstrap is thus:
knife bootstrap windows winrm <windows host> -r <run list> -VV -P <password>

This does not work with knife zero.

**Comment by sawanoboly** [comment]
The knife-zero needs remote forwarding which is provided by ssh-server. So, It can't works via winrm.
Maybe, if you install ssh-server (such as openssh, Copssh) then it will works for windows via ssh.
But I've never try it.
