### ISSUE TITLE
How to make sure the chef-repo contents (roles, ...) are on the started chef-zero instance automatically

### ISSUE THREAD

**Issue by daften** [higanworks/knife-zero#52]
When I start knife zero (e.g. to bootstrap an empty vagrant box or a digital ocean machine), the chef run complains that nothing can be found. When I start the bootstrap and let it hang when it asks for a password for ssh and check the chef-zero instance, the server is empty. Something must be wrong in my config it seems. However, I followed all the documentation I could found strictly.

My knife.rb file contents
```
cookbook_path    [File.expand_path('../../cookbooks' , __FILE__), File.expand_path('../../site-cookbooks' , __FILE__)]
node_path        File.expand_path('../../nodes' , __FILE__)
role_path        File.expand_path('../../roles' , __FILE__)
environment_path File.expand_path('../../environments' , __FILE__)
data_bag_path    File.expand_path('../../data_bags' , __FILE__)
encrypted_data_bag_secret "encrypted_data_bag_secret"
local_mode       true

knife[:bootstrap_version] = "12.4.1"
knife[:berkshelf_path] = "cookbooks"
```

And my roles are in json format.

**Comment by sawanoboly** [comment]
Thank you for using.

We can replace configuration from below..

```
cookbook_path    [File.expand_path('../../cookbooks' , __FILE__), File.expand_path('../../site-cookbooks' , __FILE__)]
node_path        File.expand_path('../../nodes' , __FILE__)
role_path        File.expand_path('../../roles' , __FILE__)
environment_path File.expand_path('../../environments' , __FILE__)
data_bag_path    File.expand_path('../../data_bags' , __FILE__)
```

TO 
```
chef_repo_path File.expand_path('../../' , __FILE__)
```

Then, could you try `knife serve` to check your chef-zero instance instead of chef-zero command.

The chef-zero command always launches with empty resources. Because storage setting is set to on memory by default.

`knife serve` subcommand launches chef-zero instance with local file system which is set by configurations in knife.rb.

**Comment by daften** [comment]
Hi,

This fixes it indeed, thanks!
I'll try to put this in documentation via a PR later today, because I can't find this in docs anywhere atm :)

**Comment by daften** [comment]
PR in #54
