### ISSUE TITLE
For some vagrant boxes, knife zero asks me for the root password

### ISSUE THREAD

**Issue by daften** [higanworks/knife-zero#56]
e.g. for box ubuntu/trusty64; for chef/centos-6.6 it doesn't happen
 The command I use is  knife zero bootstrap localhost -N vagrant -E production -u vagrant -r 'role[imindsx_aegir_base]' -P vagrant -p 2222

This should work fine. I don't understand why it then gives me as output:
```
Connecting to localhost
root@localhost's password:
```
While I clearly put vagrant as the user in the command argument.

**Comment by daften** [comment]
If I use the config knife[:ssh_user] = 'vagrant' in the knife.rb file, I'm ok. But that shouldn't be necessary IMO. the -u option should override that config.

**Comment by sawanoboly** [comment]
What version of knife-zero ? Ordering username problem was resolved by #35, maybe. 

And, could you try privatekey (-i option) which provides by `vagrant ssh-config` to authentication ?

**Comment by daften** [comment]
The problem was in my command, i used -u instead of -x, so PEBCAK :)

**Comment by sawanoboly** [comment]
Ah, it happens.
