### ISSUE TITLE
Is it possible to specify the Chef version to use?

### ISSUE THREAD

**Issue by monfresh** [higanworks/knife-zero#59]
Hi. It looks like knife zero uses Chef version 11.12.2, but I can't figure out where this version is coming from. I have Chef 12.4.1 installed locally in my Gemfile.lock. Is it possible to have knife zero use the version of Chef that is installed locally?

Thanks!

**Comment by sawanoboly** [comment]
Knife-zero will runs under bunder like other gems.
if you had seen 11.12.2 at knife zero bootstrap or converge, it version string is outputted by remote node.

**Comment by sawanoboly** [comment]
And, we can upgrade chef-client without chef-run(--no-converge) on remote node below.

```
$ knife zero bootstrap IP/HOSTNAME --bootstrap-install-command "curl chef.sh | sudo bash" --no-converge
```

Notice: This command will overwrite `client.rb`.

**Comment by monfresh** [comment]
Thanks. I'm new to Chef and still trying to understand how this all works. I'm working on a project that is using Chef Solo, Knife Solo and chef-solo-search, and I'm trying to figure out how to migrate to Chef Zero because chef-solo-search doesn't work with the latest version of Chef.

**Comment by sawanoboly** [comment]
@monfresh 

I see. These entries may be helpful for you.

- #19 | Currently using knife-solo, how easy to migrate?
- http://www.creationline.com/en/lab/8323  | Migrating from Knife-Solo to Knife-Zero #getchef
