### ISSUE TITLE
Allow role/nodes to pass in null/nil values

### ISSUE THREAD

**Issue by patcon** [higanworks/knife-zero#60]
Perhaps this is an issue with json objects in general (as compared to ruby), but I've always been in the habit of using `nil` to unset default attrs. When setting `null` in a json role, it seems it's just ignored and the default is used.

**Comment by sawanoboly** [comment]
Can you give some examples?

When null is set like below.

```
   "default_attributes": {
       "somekey": null
   }
```

It should remove or set nil to value of `somekey`. Is this what you mean?

**Comment by sawanoboly** [comment]
Ah, I was understanding. 

`nil_example/attributes/default.rb`

```
default[:somekey] = "someval"
```

`nil_example/recipe/deafult.rb`

```
file "/tmp/examplefile" do
  content node[:somekey]
end
```

`role/example.json`

```
{
  "name": "example",
  "default_attributes": {
  },
  "override_attributes": {
    "somekey": null
  },
  "run_list": [
    "recipe[nil_example]"
  ]
}
```

----

`knife zero converge`

```
#=> 
 * file[/tmp/examplefile] action create
   - create new file /tmp/examplefile
    - update content in file /tmp/examplefile from none to 621c55
   --- /tmp/examplefile	2015-09-14 22:31:10.000000000 +0000
    +++ /tmp/.examplefile20150914-5196-jgjsbo	2015-09-14 22:31:10.000000000 +0000
    @@ -1 +1,2 @@
    +someval
```

**Comment by sawanoboly** [comment]
Hmm, It might specification of deep-merge.

http://docs.chef.io/attributes.html#about-deep-merge

**Comment by sawanoboly** [comment]
It seems that there is no way to change behavior for us...

**Comment by patcon** [comment]
Ah. Hm. Well thanks very very much for investigating more than I did @sawanoboly :)
