### ISSUE TITLE
knife zero converge doesn't start the local chef zero instance it seems

### ISSUE THREAD

**Issue by daften** [higanworks/knife-zero#64]
I get output like this:
```
knife zero converge 'name:DO_db' -p 2222 -x vagrant -P vagrant -E local -r 'role[imindsx_aegir3_db]' --sudo --local-mode
localhost Starting Chef Client, version 11.8.2
localhost [2015-09-27T22:35:28+00:00] ERROR: Connection refused connecting to http://127.0.0.1:0/nodes/DO_db, retry 1/5
^C%
```

**Comment by sawanoboly** [comment]
Could you try converge with `-a knife_zero.host` ? (It needs bootstrapping with knife-zero 1.8.x)

Please check  http://knife-zero.github.io/tips/practice_with_vagrant/

**Comment by sawanoboly** [comment]
I think that you'd better use cloud servers to test the knife-zero insteard of vagrant.

When testing knife-zero with vagrant, we should know that how vagrant networking works and TCP forwarding via SSH.

**Comment by sawanoboly** [comment]
@daften any updates ?
