### ISSUE TITLE
Knife Zero removes override attributes

### ISSUE THREAD

**Issue by andrefreitas** [higanworks/knife-zero#67]
If we edit override attributes in the node, they are removed by knife zero in every converge.

**Comment by sawanoboly** [comment]
Did you add attributes under normal?
Otherwise, It will be removed.

**Comment by sawanoboly** [comment]
And, I recommend to using role or environment for set attributes to node.

**Comment by andrefreitas** [comment]
Hi, It wasn't under normal but under "override".

**Comment by sawanoboly** [comment]
https://docs.chef.io/attributes.html#attribute-types

`override` can't set to node directly. Please see Doc.

**Comment by andrefreitas** [comment]
@sawanoboly sorry, my bad, I should have read that documentation. Assumed that was Knife Zero fault.

Thanks.
