### ISSUE TITLE
always got ERROR: Net::SSH::Exception remote forwarding request failed

### ISSUE THREAD

**Issue by dfang** [higanworks/knife-zero#71]
i followed the get started guide, and i always got these errors when i run `knife zero bootstrap ip --ssh-user root -VV`
```
ERROR: Net::SSH::Exceptionremote forwarding request failed
ERROR: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/net-ssh-2.9.2/lib/net/ssh/service/forward.rb:178:in `block in remote'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:505:in `call'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:505:in `request_failure'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:466:in `dispatch_incoming_packets'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:222:in `preprocess'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/server.rb:205:in `preprocess'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/session.rb:449:in `block in preprocess'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/server_list.rb:47:in `block in each'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/server_list.rb:45:in `each'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/server_list.rb:45:in `each'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/session.rb:449:in `preprocess'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/session.rb:430:in `process'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/session.rb:417:in `block in loop'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/session.rb:417:in `loop'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/session.rb:417:in `loop'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/knife/ssh.rb:311:in `ssh_command'
/Users/dfang/.chefdk/gem/ruby/2.1.0/gems/knife-zero-1.10.1/lib/knife-zero/bootstrap_ssh.rb:29:in `ssh_command'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/knife/ssh.rb:546:in `run'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/knife/bootstrap.rb:356:in `run'
/Users/dfang/.chefdk/gem/ruby/2.1.0/gems/knife-solo-0.5.1/lib/chef/knife/bootstrap_solo.rb:25:in `run'
/Users/dfang/.chefdk/gem/ruby/2.1.0/gems/knife-zero-1.10.1/lib/chef/knife/zero_bootstrap.rb:74:in `run'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/knife.rb:405:in `block in run_with_pretty_exceptions'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/knife.rb:404:in `run_with_pretty_exceptions'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/knife.rb:203:in `run'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application/knife.rb:142:in `run'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/bin/knife:25:in `<top (required)>'
/opt/chefdk/bin/knife:54:in `load'
/opt/chefdk/bin/knife:54:in `<main>'
```

**Comment by sawanoboly** [comment]
Does your remote server allows portfowarding?
Could you check using `ssh` command before bootstrap?

**Comment by dfang** [comment]
yes, i can ssh into that server

**Comment by sawanoboly** [comment]
Ah, I'm talking about portfowading.

This command works on your environment?

```
$ ssh -L 8889:localhost:18889 $remote_server
```

It's depends on sshd_config of remote server.

**Comment by rmoriz** [comment]
This error also occurs if your connection fails while `chef-client` is still running on the node (e.g. running an external command to compile/install something that takes a lot of time).

On Ubuntu you can see the following in `/var/log/auth.log` when you try to run `knife zero converge…` again:

Apr 29 23:08:54 app sshd[22796]: error: bind: Address already in use
Apr 29 23:08:54 app sshd[22796]: error: channel_setup_fwd_listener: cannot listen to port: 18889

```shell
root@app:~# lsof |grep 18889
sshd      16808                      root    8u     IPv6            1924284       0t0        TCP ip6-localhost:18889 (LISTEN)
sshd      16808                      root    9u     IPv4            1924285       0t0        TCP localhost:18889 (LISTEN)
…

root@app:~# kill 16808

```

+ converge again

**Comment by zedtux** [comment]
I had this issue too because of the server's sshd config `AllowTcpForwarding` that was set to `no`.

I had it set to `no` because of [the SSH-Hardening cookbook](https://supermarket.chef.io/cookbooks/ssh-hardening).

Having this `AllowTcpForwarding` flag enabled will now violate [the SSH-hardening compliance profile](https://supermarket.chef.io/tools/chef-client-hardening) as it open a potential breach of the server.

Is there anyways to not being forced to have this `AllowTcpForwarding` flag enabled?

**Comment by sawanoboly** [comment]
@zedtux If you use knife-zero, you can not turn it off.

Chef has officially released a similar role function as Chef-Run.

https://www.chef.sh/docs/chef-workstation/chef-run-users-guide/

What about considering Chef-Run?

**Comment by sawanoboly** [comment]
@zedtux 

Or, there is also a choice to skip that control.

> Skipping a Control from a Profile

https://www.inspec.io/docs/reference/profiles/

**Comment by zedtux** [comment]
Thank you @sawanoboly for your comments.

`chef-run` seems to "targets a single machine" as it is written on the link you gave, which isn't really handy.

Sure I can disable the control from the profile, but I'm concerned by opening this _potential breach_.

All in all, your answer to my question "Is there anyways to not being forced to have this AllowTcpForwarding flag enabled?" seems to be "no" then.

Thank you.

**Comment by zedtux** [comment]
In the case this could help someone, I also had this error when having a stale bootstrap running forever on the server.

Killing it didn't solved the issue, restarting the server did it (fortunately the server wasn't a production one, so I could restart it).
