### ISSUE TITLE
problem with passing attributes in json format 

### ISSUE THREAD

**Issue by bogdan1980** [higanworks/knife-zero#73]
Hi,

I have a problem with passing attributes using knife zero. The values for "instance" and "ip" are not read correctly as node properties, e.g. I retrieve nil for node["instance"] from the recipe.  

 knife zero bootstrap ipaddr -r "recipe[...]" -i mykey.pem --ssh-user ec2-user --json-attributes '{"instance":"x", "ip":"y"}' --sudo

Same when using "-j" instead of "--json-attributes". Same works well when I use knife without "zero" subcommand with a Chef server.

**Comment by sawanoboly** [comment]
Thank you for using and report.
I've confirmed now. This feature was broken at adding `--json-attribute-file` function, maybe.

I'll fix it in today or tomorrow.

**Comment by sawanoboly** [comment]
@bogdan1980  please check 1.10.2 :muscle:

**Comment by bogdan1980** [comment]
It works well now :-) thank you!
