### ISSUE TITLE
[Question] Works without local_mode

### ISSUE THREAD

**Issue by allaire** [higanworks/knife-zero#75]
Hi,

Is the setting `local_mode` really mandatory? It seems to work without. Also, I see nowhere `chef_zero.enabled true`, should we include it as well in the documentation?

Also, where can I read more about the `clients/` directory knife zero (or maybe chef zero) created?

Finally, in the doc, I think we should take for granted that `knife.rb` is located in `.chef/knife.rb` as this seems like the default behaviour. In the doc we would need to adjust the paths:

```
chef_repo_path   File.expand_path('../../' , __FILE__)
cookbook_path    File.expand_path("../../cookbooks", __FILE__)
```

**Comment by allaire** [comment]
Oh and great work, just moved from knife solo to knife zero, and it feels solid and more futureproof!

**Comment by sawanoboly** [comment]
Thanks!

I seem it will not work several commands such as `knife node, search, ssh` without local_mode. Did you try them?

**Comment by allaire** [comment]
@sawanoboly Right, when I tried to do `knife data bag` it was not working, silly me :)

Is `local_mode` the same as `chef_zero.enabled true`, if not what's different?

**Comment by sawanoboly** [comment]
The local_mode option switches backend between a chef-server and a chef-zero.

It means the same as `chef_zero.enabled true` and `chef_server_url "localhost:${chef_zero.port}"`.

**Comment by allaire** [comment]
@sawanoboly Thanks so much for all these clarification!
