### ISSUE TITLE
chef-dkをインストールして、knife-zeroを入れるとchefのconflictが起こります

### ISSUE THREAD

**Issue by pikumin** [higanworks/knife-zero#83]
動作環境
Ruby 2.0.0
Chef Development Kit Version: 0.10.0
chef-client version: 12.5.1
berks version: 4.0.1
kitchen version: 1.4.2

この状態で
```chef gem install knife-zero```

をするとchef-dkからインストールされた```chef-12.5.1```とknife-zeroからインストールされた```chef-12.6.0```でConflictErrorが起きるのですが、chef-dkを使用しない方法のほうがいいのでしょうか?

初歩的な質問で申し訳ないですが、よろしくお願い致します。

**Comment by pikumin** [comment]
動作環境
Ruby 2.0.0
Chef Development Kit Version: 0.10.0
chef-client version: 12.5.1
berks version: 4.0.1
kitchen version: 1.4.2

この状態で
```chef gem install knife-zero```

をするとchef-dkからインストールされた```chef-12.5.1```とknife-zeroからインストールされた```chef-12.6.0```でConflictErrorが起きるのですが、chef-dkを使用しない方法のほうがいいのでしょうか?

初歩的な質問で申し訳ないですが、よろしくお願い致します。

**Comment by sawanoboly** [comment]
chefのバージョンが12.6未満の場合、knife-zeroは1.10.2までの対応になっています。
chef gemコマンドでバージョンを指定してください。

最新版から比べて使えない機能は、Chngelogで判断できます。

https://github.com/higanworks/knife-zero/blob/master/CHANGELOG.md

**Comment by sawanoboly** [comment]
多分コマンドはこうなります。 `chef gem install knife-zero -v "1.10.2"`

knife-zeroの最新版を使いたい場合は、こちらのコメントを参考に、Bundlerを使用してください。
https://github.com/higanworks/knife-zero/issues/45#issuecomment-169276502

**Comment by pikumin** [comment]
changelogに書いてあるのに気がつかなかったです...すいません。ありがとうございます！
