### ISSUE TITLE
Conflicts Error with Chef 12.6 on chef verify

### ISSUE THREAD

**Issue by YpNo** [higanworks/knife-zero#84]
Hi,

I have a raised conflicts error when I run "chef verify" command.
I've Chef 12.6.0 and knife-zero 1.13.0:
...
chef (12.6.0, 12.5.1)
chef-config (12.6.0, 12.5.1)
chef-dk (0.10.0)
chef-provisioning (1.5.0)
chef-provisioning-aws (1.6.1)
chef-provisioning-azure (0.4.0)
chef-provisioning-fog (0.15.0)
chef-provisioning-vagrant (0.10.0)
chef-vault (2.6.1)
chef-zero (4.4.0, 4.3.2, 1.5.6)
cheffish (1.6.0)
chefspec (4.4.0)
...
knife-zero (1.13.0)

___The error___:
Running verification for component 'openssl'
Running verification for component 'inspec'
....

/opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:2112:in `raise_if_conflicts': Unable to activate knife-zero-1.13.0, because chef-12.5.1 conflicts with chef (~> 12.6.0) (Gem::ConflictError)
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1280:in `activate'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems.rb:198:in `rescue in try_activate'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems.rb:195:in `try_activate'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:126:in `rescue in require'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from /home/lopez-m/.chefdk/gem/ruby/2.1.0/gems/knife-zero-1.13.0/lib/chef/knife/zero_apply.rb:2:in `<top (required)>'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/knife/core/subcommand_loader.rb:94:in `load'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/knife/core/subcommand_loader.rb:94:in `block in load_commands'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/knife/core/subcommand_loader.rb:94:in `each'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/knife/core/subcommand_loader.rb:94:in `load_commands'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/knife/core/subcommand_loader.rb:104:in `load_command'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/knife/core/subcommand_loader.rb:118:in `command_class_from'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/knife.rb:137:in `subcommand_class_from'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/knife.rb:198:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application/knife.rb:142:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/bin/knife:25:in `<top (required)>'
	from /opt/chefdk/bin/knife:54:in `load'
	from /opt/chefdk/bin/knife:54:in `<main>'

.../opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.2.3/lib/mixlib/shellout.rb:289:in `invalid!': Expected process to exit with [0], but received '1' (Mixlib::ShellOut::ShellCommandFailed)
---- Begin output of /usr/bin/knife exec -E true ----
STDOUT: 
STDERR: /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:2112:in `raise_if_conflicts': Unable to activate knife-zero-1.13.0, because chef-12.5.1 conflicts with chef (~> 12.6.0) (Gem::ConflictError)
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1280:in `activate'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems.rb:198:in `rescue in try_activate'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems.rb:195:in `try_activate'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:126:in `rescue in require'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from /home/lopez-m/.chefdk/gem/ruby/2.1.0/gems/knife-zero-1.13.0/lib/chef/knife/zero_apply.rb:2:in `<top (required)>'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/knife/core/subcommand_loader.rb:94:in `load'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/knife/core/subcommand_loader.rb:94:in `block in load_commands'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/knife/core/subcommand_loader.rb:94:in `each'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/knife/core/subcommand_loader.rb:94:in `load_commands'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/knife/core/subcommand_loader.rb:104:in `load_command'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/knife/core/subcommand_loader.rb:118:in `command_class_from'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/knife.rb:137:in `subcommand_class_from'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/knife.rb:198:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application/knife.rb:142:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/bin/knife:25:in `<top (required)>'
	from /usr/bin/knife:54:in `load'
	from /usr/bin/knife:54:in `<main>'
---- End output of /usr/bin/knife exec -E true ----
Ran /usr/bin/knife exec -E true returned 1
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.2.3/lib/mixlib/shellout.rb:276:in `error!'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-dk-0.10.0/lib/chef-dk/component_test.rb:99:in `block in sh!'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-dk-0.10.0/lib/chef-dk/component_test.rb:99:in `tap'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-dk-0.10.0/lib/chef-dk/component_test.rb:99:in `sh!'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-dk-0.10.0/lib/chef-dk/command/verify.rb:350:in `block (2 levels) in <class:Verify>'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-dk-0.10.0/lib/chef-dk/component_test.rb:78:in `instance_eval'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-dk-0.10.0/lib/chef-dk/component_test.rb:78:in `run_smoke_test'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-dk-0.10.0/lib/chef-dk/command/verify.rb:475:in `block (2 levels) in invoke_tests'

Kind Regards.

**Comment by sawanoboly** [comment]
Hi, Thank you for using.

First, I don't recommend that updating the chef which is included in chef-dk.

Your error message pointed out that chef command ignores chef 12.6.0.

There are two ways for resolve it.

1. install the knife-zero v1.10.2 or older.
    - `chef gem uninstall knife-zero`
    - `chef gem install knife-zero -v "1.10.2"`
2. use bundler https://github.com/higanworks/knife-zero/issues/45#issuecomment-169276502 (If you'd like to use newer knife-zero functions, please see [CHANGELOG](https://github.com/higanworks/knife-zero/blob/master/CHANGELOG.md))
    - In this case, you should include chef-dk to Gemfile.

This state is temporary until new Chef-DK will be released.

**Comment by YpNo** [comment]
Hi,
Thanks for your answer.
I downgrade knife-zero for now and I wait new release of ChefDK.

Regards.

**Comment by Joseph-R** [comment]
Chef DK 0.11.0 is available now, btw.
