### ISSUE TITLE
Option `-i` in bootstrap is not working (chef >= 12.6)

### ISSUE THREAD

**Issue by nufan00000** [higanworks/knife-zero#88]
Chef 12.6以上の場合、以下のようなコマンドを実行したときに、`-i`で渡した鍵が使われていないようです。
```
$ bundle exec knife zero bootstrap <host> --sudo -i ~/.ssh/some-key.pem
```

少し調べて見たところ、Chef12.6以降`-i`オプションは`--identity-file`から`--ssh-identity-file`に付け替えられたようです。
https://github.com/chef/chef/commit/3419637a9d287782162b3fd76041a449bc5f07e7

`--identity-file`オプションを指定すれば回避可能ではありますが、対応していただけると有難いです。

**Comment by sawanoboly** [comment]
レポートありがとうございます。 :+1:  v1.15.1 で対応しました。

**Comment by nufan00000** [comment]
早速のご対応ありがとうございます！
