### ISSUE TITLE
Converge overwrites fqdn with private address (aws); consequence is that next converge won't run untill address is manually fixed

### ISSUE THREAD

**Issue by Paul424** [higanworks/knife-zero#90]
I had expected that the automatic_attribute_whitelist from the knife.rb would skip those attributes but this seems not working because often the address is changed to the private address for ec2 nodes. It's kind of annoying because a manual fix is required each time....

I think i'm doing something wrong but i have no idea what? I thought to specify the host address myself which is no problem because i have chef-zero wrapped in fabric anyway... but it does not feel right,,

knife[:automatic_attribute_whitelist] = %w[
  fqdn
  hostname
  ipaddress
  roles
  recipes
  platform
  platform_version
  cloud
  cloud_v2
  chef_packages
]

**Comment by sawanoboly** [comment]
https://docs.chef.io/attributes.html#whitelist-attributes

> When these settings are used, any attribute not defined in a whitelist will not be saved.

Whitelist is not list of ignores.

**Comment by sawanoboly** [comment]
And, you can use address from ssh_attribute which you like with `--attribute` option .

https://knife-zero.github.io/30_subcommands/#converge


In most cases I think that "knife_zero.host" may be resolve your operation.

https://knife-zero.github.io/40_configuration/

**Comment by Paul424** [comment]
Thanks, i'll try that.
Maybe on the configuration page elaborate on this line: knife[:ssh_attribute] = "knife_zero.host" because it's not clear at once what it does; (and i usually don't copy lines of scripts i don't understand ;))
Thanks, good work!
Paul

**Comment by sawanoboly** [comment]
OK, don't mention it.
