### ISSUE TITLE
The new change about policy_group breaks knife bootstrap when policies aren't used

### ISSUE THREAD

**Issue by daften** [higanworks/knife-zero#92]
See also issue https://github.com/chef/chef/issues/4756

This commit seems to be the culprit: https://github.com/higanworks/knife-zero/commit/9844574da456a5bd82da462cebdc002c3a614744

**Comment by sawanoboly** [comment]
Oh, I see. I'll fix it on this weekend.

**Comment by daften** [comment]
Thanks! :)

**Comment by sawanoboly** [comment]
@daften Could you try `knife rehash` after update gems ?

I found that this probrem is fixed after `knife rehash`.  It seems to be caused by the change of the chef.

**Comment by sawanoboly** [comment]
@daften 
I've reported to the core. https://github.com/chef/chef/issues/4758

**Comment by daften** [comment]
That indeed fixes it, but that's not the core of the issue IMO. Setting a default policy-group is not the right way to go about it, because if i'm not mistaken, the knife zero commands will still be broken now. policy-group is still optional, so shouldn't have a default set from a plugin ...

**Comment by sawanoboly** [comment]
If I remember correctly, the plugins of Chef in the non-interference in each other, had been loaded only option when use previously.

**Comment by daften** [comment]
That's not the case anymore, so I'd say knife zero breaks the current behaviour.
Why is policy_group set by default to local? I don't see the advantage in this :s

**Comment by sawanoboly** [comment]
Reaseon, set `local` for policyfile with local mode by default. This setting by reference to https://github.com/chef/chef-dk/blob/master/lib/kitchen/provisioner/policyfile_zero.rb#L182 .

And, it is ignored when if you didn't set policy_name.

https://github.com/higanworks/knife-zero/commit/9844574da456a5bd82da462cebdc002c3a614744#diff-ec4779d5234be38ae2c57eb5ae87470fR33


I'm waiting for opinion of loading plugins behavior to Chef, to decide whether to fix. Do not worry about it too much.

For now `knife rehash` is the right way.

**Comment by sawanoboly** [comment]
OK, please check knife-zero v1.15.3 @daften

**Comment by daften** [comment]
It seems ok now, thanks :)
