### ISSUE TITLE
Response: Field 'policy_name' invalidというエラーが起こります

### ISSUE THREAD

**Issue by pikumin** [higanworks/knife-zero#93]
お世話になります。

動作環境
Ruby 2.0.0
Chef Development Kit Version: 0.12.0
chef-client version: 12.8.1
berks version: 4.3.0
kitchen version: 1.6.0

knife-zero 1.15.2

VirtualBox 5.0.16
Vagrant 1.8.1

以前はChefDKの0.10.0を使用していて、[knife zero bootstrap]コマンドが実行できたのですが、
現在同じコマンドで[knife zero bootstarp]コマンドを実行すると下記エラーが起こります。
**--------
ERROR: The data in your request was invalid
Response: Field 'policy_name' invalid
--------**

また、policy_nameオプションを追加し、実行するとChef Clientが起動する際に下記エラーが起こります。
**--------
Unexpected Error:
Chef::PolicyBuilder::Policyfile::ConfigurationError: Error loading policyfile from `policy_groups/local/policies/...': Net::HTTPServerException - 404 "Not Found "
--------**

たびたび初歩的な質問で申し訳ないですが、ご教示いただければ幸いです。
よろしくお願い致します。

**Comment by sawanoboly** [comment]
うーん、一度`knife rehash`コマンドを実行した後も同じエラーが出るでしょうか？

解消しない場合、ローカルの`knife.rb` と、リモートノードにある`/etc/chef/client.rb`の内容を、差支えの無い範囲で貼っていただけますか。

**Comment by pikumin** [comment]
ありがとうございます。

**knife.rb**
***
local_mode               true
log_level                :info
log_location             STDOUT
node_name                'xxxx'
client_key               '/xxxx/.chef/xxxx.pem'
validation_client_name   'chef-validator'
validation_key           '/etc/chef-server/chef-validator.pem'
chef_server_url          'https:443'
syntax_check_cache_path  '/xxxx/.chef/syntax_check_cache'
***
 
**client.rb**
***
log_location     STDOUT
chef_server_url  "chefzero://localhost:8889"
validation_client_name "chef-validator"
node_name "xxxx"

use_policyfile true
versioned_cookbooks true
policy_document_native_api true
policy_name xxxx
policy_group local
***

以上となっております。

また、client.rbの[use_policyfile]以下は[knife zero bootstrap]コマンド実行時、オプションに
policy_nameをつけて実行した際に追記されました。

**Comment by sawanoboly** [comment]
おや、[Policyfile](https://docs.chef.io/config_rb_policyfile.html)を使おうとしています？
でしたら https://knife-zero.github.io/tips/with_policyfile-ja/ にあるように、`chef export ./ -f`を実行する必要があります。

そうでない場合、use_policyfile以下を削除してみてください。

**Comment by pikumin** [comment]
お世話になります。

PlicyFileを使用する予定は無いのですが、``` [knife zero bootstrap] ```コマンド実行時に``` [--policy-name] ```をオプションにつけないと先ほどのエラー 
**--------
ERROR: The data in your request was invalid
Response: Field 'policy_name' invalid
--------**
が出て``` [knife zero bootstrap] ```コマンドが実行できないのです。

こちらの手順としては
1.vagrantを一度破棄する
2.vagrantを起動
3.``` [chef generate repo] ```コマンドでリポジトリ作成
4.``` [knife zero bootstrap] ```コマンドを実行
ここでエラーが起きます。

例コマンド:
 **--------
$ knife zero bootstrap xxx.xxx.xxx.xxx --ssh-user xxxxx --node-name test -i ../xxxxx/xxxx_key --sudo
...
Creating new client for test
Creating new node for test
ERROR: The data in your request was invalid
Response: Field 'policy_name' invalid
...
--------**

以上となります。
お忙しい中申し訳ないですが、よろしくお願い致します。

**Comment by sawanoboly** [comment]
何となくChef側の挙動変更で心当たりがあります。

その環境の場合、Chef-DKとknife-zeroをインストールした後に `knife rehash` コマンドを実行してプラグインのロード処理を最適化すれば`zero bootstrap`を実行できるはずなので、一旦それでどうでしょうか。

こちらも何らか対策をして、近いうちにKnife-Zeroを更新する予定です。

**Comment by pikumin** [comment]
ありがとうございます。

``` [knife rehash] ```コマンドを実行したのですがやはり``` policy_name ```のエラーが出ます。。。

**---------------------------
Creating new client for test
Creating new node for test
ERROR: The data in your request was invalid
Response: Field 'policy_name' invalid
---------------------------**

手順としまして下記となります
1.Knife-Zero(1.15.2)、ChefDK(0.12.0)を一旦削除して再インストール
2.``` [knife configure] ```コマンドでknife.rb作成
3.``` [knife rehash] ```コマンド実行
4.``` [chef genetate repo] ```コマンドでリポジトリ作成
5.``` [knife zero bootstrap] ```コマンド実行

また、ChefDKとknife-Zeroを以前のバージョンに戻すと
``` [knife zero bootstrap] ```コマンドを実行する事ができます。

以上となります。
どうぞよろしくお願い致します。

**Comment by sawanoboly** [comment]
どうもknife.rbが複数あるような気がします。

`knife zero diagnose` でconfig_fileの値が使用している`knife.rb`のパスを確認できるのですが、そのファイルパスは想定している値でしょうか？

**Comment by sawanoboly** [comment]
あと、これについては

> そうでない場合、use_policyfile以下を削除してみてください。

client.rbの次の部分を指しています。

```
use_policyfile true
versioned_cookbooks true
policy_document_native_api true
policy_name xxxx
policy_group local
```

**Comment by sawanoboly** [comment]
あ、ローカルに`nodes/xxxx.json` が残っていませんか？ 一度ポリシーを指定したら、nodeファイルを消さないと駄目かもしれません。

**Comment by pikumin** [comment]
お世話になっております。

``` [knife zero diagnose] ```コマンドで確認したのですが``` knife.rb ```のパスは想定している
値でした。
また、ルートディレクトリより``` [find] ```コマンドで``` knife.rb ```を検索したのですがfileは1つでした。

``` client.rb ```につきましては``` [knife zero bootstarp] ```ができず、
リモートにchefがインストールされていないので作成されておりません。
(``` --policy-name ```オプションをつけた際はリモートにchefがインストールされますが、``` policy-group ```のエラーになります。)

``` nodes/xxxx.json ```につきましても``` [knife zero bootstarp] ```でエラーになるのでjsonファイルは作成されていないです。

もし、よろしければインストール手順などを差し支えない程度で教えていただけないでしょうか？
こちらも同じ手順で実行させていただきます。

どうぞよろしくお願い致します。

**Comment by sawanoboly** [comment]
うーん、他で気になるところと言うと、knife.rbの`chef_server_url`ですかね。この行をコメントアウトするとよいかもしれません。

なおインストール手順の件、私は開発の都合上Chef-DKパッケージを使わないので、次の手順で使用しています。

https://knife-zero.github.io/10_install-ja/ の`Bundlerの例`

**Comment by pikumin** [comment]
お世話になっております。

色々試してみたのですがやはり、``` policy_name ```のエラーが出てしまいます。

``` chef-zero ```の``` nodes_endpoint.rb ```の

```
if data.has_key?("policy_name") && policy_name_invalid?(data["policy_name"])
    return error(400, "Field 'policy_name' invalid", :pretty => false)
end
```

のエラー文が出ているようです。

とりあえずChefDKを0.11.0に下げたところ``` knife zero bootstrap ```コマンドが
動きましたのでこの状態で使用したいと思います。

-----------------------
Chef Development Kit Version: 0.11.0
chef-client version: 12.7.2
berks version: 4.1.1
kitchen version: 1.5.0

knife-zero 1.15.3

VirtualBox 5.0.16
Vagrant 1.8.1

---------------------------

お忙しい中、色々とありがとうございます。

**Comment by sawanoboly** [comment]
はい。

もし、まっさらな状態(VMなど)にインストールして再現する手順が分かれば教えて下さい。Issueを一旦閉じておきます。

**Comment by pikumin** [comment]
お世話になっております。

エラーの原因がわかりましたので、ご報告致します。

``` knife.rb ```から``` [validation_key] ```の一行を消すと``` [knife zero bootstrap] ```
コマンドが実行できました。

試しに前バージョンの``` ChefDK(0.10.0) ```をインストールして``` knife.rb ```を作成し、
``` [knife zero bootstrap] ```コマンドを実行すると正常にnodeが追加されるのですが、

``` ChefDK(0.12.0) ```の場合だと``` [validation_key] ```の一行があれば

>
> Creating new client for test
> Creating new node for test
> ERROR: The data in your request was invalid
> Response: Field 'policy_name' invalid
>

が出るようです。

以上となります。
どうぞよろしくお願い致します。

**Comment by pikumin** [comment]
お世話になります。

再現する手順をまとめましたのでご報告致します。
また、比較する為``` [ChefDK(0.10.0)] ```、``` [ChefDK(0.12.0)] ```
の場合を実行しました。

``` 
・環境
VirtualBox 5.0.16
Vagrant 1.8.1

ChefDKをアンインストール(.chef、.chefdkなども削除)
[chef]コマンドが無い状態になります。

vagrantの作成として下記手順を実行します。

1.[vagrant1]、[vagrant2]ディレクトリを作成し、それぞれ中に入って
[vagrant init]コマンドを実行し、[Vagrantfile]を作成します。

2.[Vagrantfile]を修正します。
[config.vm.box]に[CentOS7.1]のboxを使用します。

[config.vm.network]のコメントを外して任意のPrivateIPを振ります。
(ここでは[192.168.33.10]、[192.168.33.11]とします。)
 ```

**・ChefDK(0.10.0)の場合**
1.``` [vagrant1] ```ディレクトリに入って``` [vagrant up] ```コマンド
でvagrantを起動します。

2.``` [ChefDK(0.10.0)] ```をダウンロードして、インストール(chefdk-0.10.0-1)

3.``` [chef -v] ```コマンドでバージョン確認

 ---
Chef Development Kit Version: 0.10.0
chef-client version: 12.5.1
berks version: 4.0.1
kitchen version: 1.4.2
 ---

4.``` [chef gem] ```で``` [knife-zero(1.10.2)] ```をインストール

5.``` [knife configure] ```コマンドで``` knife.rb ```を作成(全てEnterで作成)

6.``` [knife.rb] ```に``` [local_mode true] ```を追記

5.``` [chef generate repo] ```でリポジトリを作成

6.作成したリポジトリに入って``` [knife zero bootstrap] ```コマンドを実行
`knife zero bootstrap 192.168.33.10 --ssh-user vagrant --node-name test1 -i .../private_key --sudo`

7.正常にchefがインストールされます

**ChefDKをアンインストール(.chef、.chefdkなども削除)**

**・ChefDK(0.12.0)の場合**
1.``` [vagrant2] ```ディレクトリに入って``` [vagrant up] ```コマンド
でvagrantを起動します。

2.``` [ChefDK(0.12.0)] ```をダウンロードして、インストール(chefdk-0.12.0-1)

3.``` [chef -v] ```コマンドでバージョン確認
 ---
Chef Development Kit Version: 0.12.0
chef-client version: 12.8.1
berks version: 4.3.0
kitchen version: 1.6.0
 ---

4.``` [chef gem] ```で``` [knife-zero(1.15.3)] ```をインストール

5.``` [knife configure] ```コマンドで``` knife.rb ```を作成(全てEnterで作成)

6.``` [knife.rb] ```に``` [local_mode true] ```を追記

5.``` [chef generate repo] ```でリポジトリを作成

6.作成したリポジトリに入って``` [knife zero bootstrap] ```コマンドを実行
`knife zero bootstrap 192.168.33.11 --ssh-user vagrant --node-name test2 -i .../private_key --sudo`

7.エラーがでます
 ---
**Creating new client for test2
Creating new node for test2
ERROR: The data in your request was invalid
Response: Field 'policy_name' invalid**
 ---
8.``` knife.rb ```の``` [validation_key] ```の一行を削除
	
9.再度、``` [knife zero bootstrap] ```コマンドを実行
`knife zero bootstrap 192.168.33.11 --ssh-user vagrant --node-name test2 -i .../private_key --sudo`

10.正常にchefがインストールされます

以上となります。
どうぞよろしくお願い致します。

**Comment by sawanoboly** [comment]
再現手順ありがとうございます。

> 5.[knife configure]コマンドでknife.rbを作成(全てEnterで作成)

なるほど、`knife configure`を使っているケースがあるんですね。`knife configure`は基本的にClient/Server環境を使用するための設定を作成するコマンドなので、Knife-Zeroでは不要な設定が入ると思います。
Knife-Zeroドキュメントでもそのような案内をしていないし、`knife.rb`に設定できるすべての要素をカバーするわけにも行かない (Knife-Zeroでは不要な設定を無視するようにすると、Chef本来の機能が潰れることがあるかもしれない) ため、ちょっとサポート外ですね。

**Comment by pikumin** [comment]
なるほど。ではknife-zeroを使用する場合、knife.rbは``` [local_mode true] ```のみでいいのでしょうか？

**Comment by sawanoboly** [comment]
こちらの『ざっくりしたおすすめ設定』などを参考にしていただくと良いかと思います。

https://knife-zero.github.io/40_configuration-ja/ 

`chef generate repo`したChef-Repoの直下に`knife.rb`を設置で大丈夫です。

**Comment by pikumin** [comment]
すいません。``` knife.rb ```をhttps://knife-zero.github.io/20_getting_started-ja/
を見て書き直していました。参考URLありがとうございます！
