### ISSUE TITLE
Zero Converge with json-attribute

### ISSUE THREAD

**Issue by sawanoboly** [higanworks/knife-zero#97]
http://qiita.com/sawanoboly/items/4f363909615d8a76e9e5#comment-5be5e2c238fa695eb8f1

**Comment by sawanoboly** [comment]
こんな感じになるかな。

- chef-clientからjson-attributeのオプションを拝借
- chef-client実行前に転送
- CLIオプション追加

**Comment by sawanoboly** [comment]
追加先の優先度がNormalになりそうなので、結局残るのかな？

**Comment by sawanoboly** [comment]
永続でもよければ実装。

**Comment by sawanoboly** [comment]
convergeが対象を複数とるので、永続化わりと危なっかしいな。

**Comment by fuku2014** [comment]
chef-clientのjson-attributeを使う以上永続化になっちゃうんですよね。

json-attributeを指定する場合はセットでoverride_runlistも指定する様にして、nodeを更新させないとかは...微妙ですかね？

**Comment by sawanoboly** [comment]
ちょっと整理してみます。

- json-attributeのみ => 永続化する
- json-attribute + override_runlist (有効なランリスト) => Nodeのsaveがスキップされる
-- 多分この挙動がベスト
- json-attribute + override_runlist (空文字列) => 元のrun_listが優先される
-- 内部的に強制でダミーの`override_runlist`しようとしてもダメ。

なるほど、`json-attribute`を使うときは空文字以外のoverride_runlistを併用するようにオプションチェックという案は良さそうです。

**Comment by sawanoboly** [comment]
@fuku2014 Rubygemsにv1.16.0.pre1としてリリースしたのでよければお試しください。

オプションは `--json-attributes`で、`--override-runlist `との併用を必須にしてあります。ローカルのNodeオブジェクトは更新しません。

**Comment by fuku2014** [comment]
sshやidentity-fileのpasswordが対話的に入力できないんですね。
これはchef-clientの仕様でしょうか？
ssh-agent設定していれば問題無く動作できました。

**Comment by sawanoboly** [comment]
> sshやidentity-fileのpasswordが対話的に入力できない

`zero converge`は複数台が対象になったり、一度に何度か接続します。
ベースが[knife ssh](https://docs.chef.io/knife_ssh.html)で、パスフレーズの使い回しの仕組みを作っていないので、基本的にssh-agent推奨になります。

多少それっぽい議論もされてるようです。 https://github.com/chef/chef/issues/4881

**Comment by sawanoboly** [comment]
v1.16.0 のpre無し版リリースとドキュメントを更新したのでCloseします。
