### ISSUE TITLE
default attributes in node file?

### ISSUE THREAD

**Issue by allaire** [higanworks/knife-zero#99]
Hi, I just noticed that default attributes are stored in my node json files.

Normally, only normal attributes are stored into the nodes object. I often do things like these:

```
credentials = Chef::EncryptedDataBagItem.load("secrets", "credentials")

node.default["mmonit"]["license_owner"] = credentials["mmonit_license_owner"]
node.default["mmonit"]["license"] = credentials["mmonit_license"]
```

But then my node json files contain the encrypted values in plain text.

how can I get around this @sawanoboly ?

**Comment by allaire** [comment]
`A default attribute is automatically reset at the start of every chef-client run and has the lowest attribute precedence. Use default attributes as often as possible in cookbooks.`

Why is it persisted in the node object? Shouldn't it be reset each time and not persisted?

**Comment by sawanoboly** [comment]
hmm...

I think that EncryptedDataBagItem should not expand into attributes. I usually extract  data from EncryptedDataBagItem from recipe directly.

> Why is it persisted in the node object? 

What is set priority of saved attribute ?

**Comment by allaire** [comment]
> What is set priority of saved attribute ?

How can I check that

**Comment by allaire** [comment]
@sawanoboly my default attributes are set in a wrapper cookbook. I don't use the data bag value directly because I wrap some other cookbook which define their password in attribute. 

Thanks

**Comment by allaire** [comment]
@sawanoboly Just had a conversation in #chef and it seems normal default attributes are saved in the nodes.

How could I work-around this issue? Do you gitignore your `nodes/` directory?

**Comment by sawanoboly** [comment]
@allaire 

Could you try `default_attribute_whitelist` ?

For example,

 in client.rb

```
default_attribute_whitelist ['mmonit/license_owner']
```

It saves listed keys only like below.

```
  "default": {
    "mmonit": {
      "license_owner": "test"
    }
  },
```

You can select keys which will be saved to node object.

**Comment by allaire** [comment]
@sawanoboly do you have a good set of defaults for `default_attribute_whitelist` ? What do you normally keep in your node file?

**Comment by sawanoboly** [comment]
hmm... I don't have good set.

I recommend to start with empty list. Because default attributes are not  useful to search.

in `knife.rb`

```
knife[:default_attribute_whitelist] = []
```

bootstrap adds `client.rb` below

```
default_attribute_whitelist []
```

**Comment by allaire** [comment]
@sawanoboly cool it works! Is there a command that I can run to update client.rb? `knife zero bootstrap` reset my run list

**Comment by sawanoboly** [comment]
@allaire 

There are 3 ways to update client.rb on remote node without saving node.

- bootstrap with `--no-converge` option.  (be careful, please test before run at all.)
- use recipe (zero converge or zero apply)
- edit by hand

**Comment by sawanoboly** [comment]
Because I had forgotten to write in the document. I've updated.  https://knife-zero.github.io/40_configuration/

Thanks

**Comment by allaire** [comment]
@sawanoboly Thank you, unfortunately the `--no-converge` option is returning:

`knife zero bootstrap foo.exemple.com --ssh-user foo --no-converge`

```
Doing old-style registration with the validation key at ...
Delete your validation key in order to use your user credentials instead
-----> Existing Chef installation detected
Starting the first Chef Client run...
Execution of Chef-Client has been canceled due to bootstrap_converge is false.
Execution of Chef-Client has been canceled due to bootstrap_converge is false.
```

**Comment by sawanoboly** [comment]
@allaire It is the correct behavior of `--no-converge`.

`--no-converge` option installs chef-client and put(update) client.rb which is generated from configuration at knife.rb.

did you write `knife[:default_attribute_whitelist] = []` to knife.rb ? This configuration appends default_attribute_whitelist  to `client.rb`.

**Comment by allaire** [comment]
@sawanoboly Thanks, that make sense. `--no-converge` is from knife-zero right? There is no equivalent in Chef directly correct? (https://docs.chef.io/knife_bootstrap.html)

Thanks again for all your support, you're aweosme 👍

**Comment by sawanoboly** [comment]
@allaire Yes, `--no-converge` is added by knife-zero.
